export const IS_DEBUG = window.location.search.indexOf('debug') >= 0;

export const GRID_SIZE = 20;

export const MOVE_CURSOR = 'MOVE_CURSOR';
export const UPSERT_BLOCK = 'UPSERT_BLOCK';
export const CREATE_BLOCK = 'CREATE_BLOCK';
export const SHOW_NEW_BLOCK_PROMPT = 'SHOW_NEW_BLOCK_PROMPT';
export const CLOSE_NEW_BLOCK_PROMPT = 'CLOSE_NEW_BLOCK_PROMPT';
export const CONNECT_FROM_INPUT = 'CONNECT_FROM_INPUT';
export const CONNECT_FROM_OUTPUT = 'CONNECT_FROM_OUTPUT';
export const CONNECT_FROM_INPUT_TYPED_LETTER = 'CONNECT_FROM_INPUT_TYPED_LETTER';
export const CONNECT_FROM_OUTPUT_TYPED_LETTER = 'CONNECT_FROM_OUTPUT_TYPED_LETTER';
export const NEW_BLOCK_NAME = '__NEW_BLOCK__';
